apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngsa-memory
  namespace: ngsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngsa-memory
  template:
    metadata:
      labels:
        app: ngsa-memory
        version: beta-0511-0157
        deploy: 21-05-11-01-57-37
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/ngsa-app:beta
          imagePullPolicy: Always

          args: 
          - --in-memory
          - --prometheus
          - --zone
          - az-central
          - --region
          - Central

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: ngsa-memory
  namespace: ngsa
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ngsa-memory

---

apiVersion: v1
kind: Service
metadata:
  name: ngsa-memory-np
  namespace: ngsa
  labels:
    app: ngsa-memory

spec:
  type: NodePort
  selector:
    app: ngsa-memory
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loderunner
  namespace: ngsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loderunner
  template:
    metadata:
      labels:
        app: loderunner
        version: beta-0511-0157
        deploy: 21-05-11-01-57-37
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/ngsa-lr:beta
          imagePullPolicy: Always

          args: 
          - --sleep
          - "1000"
          - --run-loop
          - --server
          - http://ngsa-memory:8080
          - --files
          - benchmark.json
          - --prometheus
          - --zone
          - az-central
          - --region
          - Central

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: loderunner
  namespace: ngsa
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: loderunner

---

apiVersion: v1
kind: Service
metadata:
  name: loderunner-np
  namespace: ngsa
  labels:
    app: loderunner

spec:
  type: NodePort
  selector:
    app: loderunner
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080
